ModelName : SUMBT


SUMBT:
    hidden_dim: 300
    num_rnn_layers: 1
    zero_init_rnn: False
    max_seq_length: 128
    max_label_length: 12
    attn_head: 4
    fix_utterance_encoder: False
    task_name: sumbtgru
    distance_metric: euclidean
    model_name_or_path: dsksd/bert-ko-small-minimal
    warmup_ratio: 0.1
    learning_rate: !!python/float 5e-5
    weight_decay: 0.01
    num_train_epochs: 10



TRADE:
    data_dir: /opt/ml/input/data/train_dataset
    model_dir: /opt/ml/results
    train_batch_size: 16
    eval_batch_size: 32
    learning_rate: 0.0001
    adam_epsilon: !!python/float 1e-08
    max_grad_norm: 1.0
    num_train_epochs: 30
    warmup_ratio: 0.1
    random_seed: 42
    model_name_or_path: monologg/koelectra-base-v3-discriminator
    hidden_size: 768
    vocab_size: 35000
    hidden_dropout_prob: 0.1
    proj_dim: null
    teacher_forcing_ratio: 0.5
    n_gate: 3
